name = "caniuse-embed"
compatibility_date = "2025-10-08"
pages_build_output_dir = "./public"

services = [
  { binding = "API", service = "caniuse-embed-api" }
]

# [build]
# command = "npm run build"

# [assets]
# directory = "./public"
